import type { PlannerData, Goal } from './types';

function formatField(value: string | undefined, fallback = '(Not filled)'): string {
  if (!value || value.trim() === '') {
    return fallback;
  }
  return value.trim();
}

function formatThemes(themes: string[]): string {
  const filled = themes.filter(t => t.trim() !== '');
  if (filled.length === 0) {
    return '(Not filled)';
  }
  return filled.map((t, i) => `${i + 1}. ${t}`).join('\n');
}

function formatGoals(goals: Goal[]): string {
  const filled = goals.filter(g => g.description.trim() !== '');
  if (filled.length === 0) {
    return '(Not filled)';
  }
  return filled.map((g, i) => {
    const parts = [`### Goal ${i + 1}: ${g.description || '(No description)'}`];
    if (g.metric.trim()) {
      parts.push(`- **Metric:** ${g.metric}`);
    }
    if (g.successDefinition.trim()) {
      parts.push(`- **Success looks like:** ${g.successDefinition}`);
    }
    return parts.join('\n');
  }).join('\n\n');
}

export function generateMarkdownPlan(data: PlannerData): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return `# 2026 Annual Plan
*Generated by Tide Planner on ${dateStr}*

---

## Part 1: 2025 in Review

### Significant Events
${formatField(data.significantEvents)}

### Achievements
${formatField(data.achievements)}

### Challenges Faced
${formatField(data.challenges)}

### Lessons Learned
${formatField(data.lessonsLearned)}

---

## Part 2: 2025 Patterns

### What Worked Well
${formatField(data.whatWorked)}

### What Didn't Work
${formatField(data.whatDidntWork)}

### Energy Sources
${formatField(data.energySources)}

### Energy Drains
${formatField(data.energyDrains)}

---

## Part 3: 2026 Direction

### Key Themes
${formatThemes(data.themes)}

### Not Doing List
${formatField(data.notDoingList)}

---

## Part 4: 2026 Goals

${formatGoals(data.goals)}

---

## Part 5: Quarterly Roadmap

### Q1 (January - March)
${formatField(data.q1Milestones)}

### Q2 (April - June)
${formatField(data.q2Milestones)}

### Q3 (July - September)
${formatField(data.q3Milestones)}

### Q4 (October - December)
${formatField(data.q4Milestones)}

### Habits & Systems
${formatField(data.habits)}

---

## Part 6: Risks & Support

### Potential Risks & Obstacles
${formatField(data.risks)}

### Contingency Plans
${formatField(data.contingencyPlans)}

### Support & Resources Needed
${formatField(data.supportNeeded)}

---

*Close 2025. Set the tide for 2026.*
`;
}

export function copyToClipboard(text: string): Promise<boolean> {
  return navigator.clipboard.writeText(text)
    .then(() => true)
    .catch(() => {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      try {
        document.execCommand('copy');
        return true;
      } catch {
        return false;
      } finally {
        document.body.removeChild(textarea);
      }
    });
}

export function downloadAsMarkdown(content: string, filename = '2026-annual-plan.md'): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
